/**
 * One-off pass over src/data/products.generated.ts: a batch of products was
 * imported with picsum.photos placeholder images (seeded random stock
 * photography that never matches the actual product — e.g. "Nike Air
 * Runner" showing an unrelated photo). This clears `image` (and `images`,
 * where present) on any product sourced from picsum.photos, leaving
 * everything else about the product untouched. The storefront falls back to
 * a plain placeholder tile wherever `image` is empty.
 *
 * Usage: npx tsx scripts/clear-mismatched-images.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Product } from "../src/data/products";

const ROOT = resolve(import.meta.dirname, "..");
const outPath = resolve(ROOT, "src/data/products.generated.ts");

async function loadProducts(): Promise<Product[]> {
  const url = `${pathToFileURL(outPath).href}?t=${Date.now()}`;
  const mod = (await import(url)) as { generatedProducts: Product[] };
  return mod.generatedProducts;
}

function toSource(products: Product[]): string {
  const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  return `// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run \`npm run import:products -- <csv>\` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = ${body};
`;
}

const isMismatched = (url: string) => url.includes("picsum.photos");

async function main() {
  const products = await loadProducts();
  let cleared = 0;

  const updated = products.map((p) => {
    if (!isMismatched(p.image)) return p;
    cleared++;
    const { images, ...rest } = p;
    return { ...rest, image: "" };
  });

  writeFileSync(outPath, toSource(updated), "utf-8");
  console.log(`Cleared mismatched image on ${cleared}/${products.length} product(s) → ${outPath}`);
}

main();
