/**
 * One-off enrichment pass over src/data/products.generated.ts: attaches extra
 * angle images (`Product.images`) from a supplemental CSV that has already
 * been import-products'd for its base fields (price/name/etc). This script
 * only ever adds `images` — it never touches offers, price, or anything
 * else the normal import pipeline owns.
 *
 * Expected CSV columns: product_url, image_1, image_2, image_3, image_4
 * (any of image_2..4 may be blank). Each row is matched to an existing
 * product by finding an offer whose `productUrl` equals the row's
 * `product_url` — the same identity the main importer keys offers on.
 * Rows that don't match any known offer are reported and skipped, not
 * silently dropped.
 *
 * Usage: npx tsx scripts/enrich-images.ts <path-to-csv>
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Product } from "../src/data/products";

const ROOT = resolve(import.meta.dirname, "..");
const outPath = resolve(ROOT, "src/data/products.generated.ts");

function parseCsvLine(line: string): string[] {
  const cells: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      cells.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  cells.push(cur);
  return cells;
}

function parseCsv(text: string): Record<string, string>[] {
  const lines = text.split(/\r\n|\n|\r/).filter((l) => l.trim().length > 0);
  if (lines.length === 0) return [];
  const header = parseCsvLine(lines[0]).map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const cells = parseCsvLine(line);
    const row: Record<string, string> = {};
    header.forEach((col, idx) => {
      row[col] = (cells[idx] ?? "").trim();
    });
    return row;
  });
}

async function loadProducts(): Promise<Product[]> {
  const url = `${pathToFileURL(outPath).href}?t=${Date.now()}`;
  const mod = (await import(url)) as { generatedProducts: Product[] };
  return mod.generatedProducts;
}

function toSource(products: Product[]): string {
  const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  return `// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run \`npm run import:products -- <csv>\` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = ${body};
`;
}

async function main() {
  const csvPath = process.argv[2];
  if (!csvPath) {
    console.error("Usage: npx tsx scripts/enrich-images.ts <path-to-csv>");
    process.exit(1);
  }

  const rows = parseCsv(readFileSync(resolve(csvPath), "utf-8"));
  const byProductUrl = new Map<string, string[]>();
  for (const row of rows) {
    const images = [row.image_1, row.image_2, row.image_3, row.image_4].filter(Boolean);
    if (row.product_url && images.length) byProductUrl.set(row.product_url, images);
  }

  const products = await loadProducts();
  let matched = 0;
  const unmatchedUrls = new Set(byProductUrl.keys());

  const updated = products.map((p) => {
    const hit = p.offers.find((o) => byProductUrl.has(o.productUrl));
    if (!hit) return p;
    const images = byProductUrl.get(hit.productUrl)!;
    unmatchedUrls.delete(hit.productUrl);
    matched++;
    return { ...p, images };
  });

  writeFileSync(outPath, toSource(updated), "utf-8");
  console.log(`Matched ${matched}/${byProductUrl.size} CSV row(s) to products → ${outPath}`);
  if (unmatchedUrls.size) {
    console.log(`Unmatched product_url(s) (${unmatchedUrls.size}):`);
    for (const u of unmatchedUrls) console.log(`  ${u}`);
  }
}

main();
