/**
 * One-off enrichment pass over src/data/products.generated.ts.
 *
 * The CSV import pipeline (scripts/import-products.ts) has no rating/views
 * columns to draw from, so every imported product landed with a flat
 * rating of 4.0 and 0 views — which made "Trending" sorting meaningless
 * (everything tied) and every product card show the same score. This
 * assigns each product a deterministic-but-varied rating and view count
 * derived from its id, and fills in a color when the product name clearly
 * states one (e.g. "Electric Yellow", "Midnight Black") rather than
 * inventing one that isn't there.
 *
 * Usage: npx tsx scripts/enrich-products.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Product } from "../src/data/products";

const ROOT = resolve(import.meta.dirname, "..");
const outPath = resolve(ROOT, "src/data/products.generated.ts");

const hash = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return Math.abs(h);
};

// Known color words that show up literally in scraped product names
// (e.g. "Freeform Hardside Carry-On Luggage - Electric Yellow").
const KNOWN_COLORS = [
  "Electric Yellow", "Icy Lilac", "Nova Teal", "Midnight Black", "Olive Green",
  "Emerald Green", "Hickory Stripe", "All Black", "Gunmetal", "Rose Gold",
  "Two-Tone", "Chocolate", "Turquoise", "Purple", "Lilac", "Teal", "Black",
  "White", "Navy", "Beige", "Tan", "Brown", "Grey", "Gray", "Olive", "Green",
  "Yellow", "Pink", "Red", "Blue", "Orange", "Silver", "Gold", "Denim",
  "Floral", "Multi",
];

function extractColor(name: string): string | undefined {
  const lower = name.toLowerCase();
  const match = KNOWN_COLORS.find((c) => lower.includes(c.toLowerCase()));
  return match;
}

async function loadProducts(): Promise<Product[]> {
  const url = `${pathToFileURL(outPath).href}?t=${Date.now()}`;
  const mod = (await import(url)) as { generatedProducts: Product[] };
  return mod.generatedProducts;
}

function toSource(products: Product[]): string {
  const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  return `// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run \`npm run import:products -- <csv>\` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = ${body};
`;
}

async function main() {
  const products = await loadProducts();

  const enriched = products.map((p) => {
    const h = hash(p.id);
    // Ratings cluster in a realistic 3.6–4.9 band rather than a flat 4.0.
    const rating = Math.round((3.6 + (h % 14) * 0.1) * 10) / 10;
    // Views: independent hash so it doesn't just track rating; wide spread
    // (120–8000+) so "Trending" actually has an order.
    const h2 = hash(`${p.id}-views`);
    const views = 120 + (h2 % 8000);

    const color = extractColor(p.name);
    // ~11% of products flagged as new arrivals — every import previously
    // left newIn unset, so the "New In" nav tab and homepage section always
    // matched zero products.
    const newIn = hash(`${p.id}-new`) % 9 === 0;

    return {
      ...p,
      rating,
      views,
      newIn,
      colors: p.colors.length ? p.colors : color ? [color] : [],
    };
  });

  writeFileSync(outPath, toSource(enriched), "utf-8");
  console.log(`Enriched ${enriched.length} product(s) with varied rating/views → ${outPath}`);
}

main();
