/**
 * One-off pass over src/data/products.generated.ts: several CSV batches
 * (mostly the luxury/travel brands — Gucci, Prada, Net-a-Porter, Tumi, etc.)
 * carried unrealistic prices (totes and blazers listed at $50k-$120k+).
 * This rescales any offer whose USD price exceeds a realistic ceiling for
 * its product category down into a genuine range, picking a
 * deterministic-but-varied target from the product id (not clamping every
 * outlier to the same number) and rescaling `originalPrice` by the same
 * ratio so the discount percentage is preserved. Offers already within a
 * sane range are left untouched.
 *
 * Usage: npx tsx scripts/fix-prices.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Product } from "../src/data/products";

const ROOT = resolve(import.meta.dirname, "..");
const outPath = resolve(ROOT, "src/data/products.generated.ts");

const BASE_TO_USD = 1 / 83;
const toUsd = (n: number) => n * BASE_TO_USD;
const toBase = (usd: number) => Math.round(usd / BASE_TO_USD);

// Realistic max retail USD price per shop category — generous enough to
// cover genuine premium/luxury pieces, but not five-figure basics.
const CEILING_USD: Record<string, number> = {
  jewelry: 2500,
  watches: 2500,
  "mens-watches": 2500,
  beauty: 150,
  "beauty-lifestyle": 150,
  grooming: 120,
  bags: 3000,
  "mens-bags": 3000,
  shoes: 600,
  "mens-shoes": 600,
  sneakers: 350,
  "kids-shoes": 150,
  "baby-clothing": 100,
  clothing: 2000,
  "mens-clothing": 2000,
  "kids-clothing": 150,
  sportswear: 300,
  "mens-sportswear": 300,
  accessories: 800,
  "mens-accessories": 800,
  travel: 800,
  "lifestyle-accessories": 800,
  fitness: 300,
  home: 500,
  electronics: 500,
};
const DEFAULT_CEILING = 800;

const hash = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return Math.abs(h);
};

async function loadProducts(): Promise<Product[]> {
  const url = `${pathToFileURL(outPath).href}?t=${Date.now()}`;
  const mod = (await import(url)) as { generatedProducts: Product[] };
  return mod.generatedProducts;
}

function toSource(products: Product[]): string {
  const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  return `// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run \`npm run import:products -- <csv>\` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = ${body};
`;
}

async function main() {
  const products = await loadProducts();
  let fixed = 0;

  const updated = products.map((p) => {
    const ceiling = CEILING_USD[p.category] ?? DEFAULT_CEILING;
    let touched = false;

    const offers = p.offers.map((o, i) => {
      const usd = toUsd(o.price);
      if (usd <= ceiling) return o;

      touched = true;
      fixed++;
      // Deterministic target within [40%, 100%] of the category ceiling —
      // varied per offer, never just clamped to the same ceiling value.
      const h = hash(`${p.id}-${i}-price`);
      const target = Math.round(ceiling * (0.4 + (h % 61) / 100));
      const ratio = target / usd;

      return {
        ...o,
        price: toBase(target),
        originalPrice: Math.max(toBase(target), Math.round(o.originalPrice * ratio)),
      };
    });

    if (!touched) return p;
    return { ...p, offers };
  });

  writeFileSync(outPath, toSource(updated), "utf-8");
  console.log(`Rescaled ${fixed} offer(s) across ${products.length} product(s) → ${outPath}`);
}

main();
