/**
 * One-off pass that remaps every product's `category` field in
 * src/data/products.generated.ts onto the canonical shop-category taxonomy
 * (see src/lib/categorize.ts for why this is necessary — accumulated CSV
 * imports left ~74 different raw category strings, most of which the
 * Department/Category filters had never heard of, so filtering silently
 * dropped those products to zero results).
 *
 * Usage: npx tsx scripts/normalize-categories.ts
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Product } from "../src/data/products";
import { canonicalCategory } from "../src/lib/categorize";

const ROOT = resolve(import.meta.dirname, "..");
const outPath = resolve(ROOT, "src/data/products.generated.ts");

async function loadProducts(): Promise<Product[]> {
  const url = `${pathToFileURL(outPath).href}?t=${Date.now()}`;
  const mod = (await import(url)) as { generatedProducts: Product[] };
  return mod.generatedProducts;
}

function toSource(products: Product[]): string {
  const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  return `// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run \`npm run import:products -- <csv>\` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = ${body};
`;
}

async function main() {
  const products = await loadProducts();
  let changed = 0;

  const normalized = products.map((p) => {
    const category = canonicalCategory({
      brand: p.brand,
      rawCategory: p.category,
      subcategory: p.subcategory,
      gender: p.gender,
      name: p.name,
    });
    if (category !== p.category) changed++;
    return { ...p, category };
  });

  writeFileSync(outPath, toSource(normalized), "utf-8");
  console.log(`Normalized category for ${changed}/${normalized.length} product(s) → ${outPath}`);
}

main();
