/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as FlashDealsRouteImport } from './routes/flash-deals'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as SalesCalendarRouteImport } from './routes/sales-calendar'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DealSlugRouteImport } from './routes/deal.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SaleSlugRouteImport } from './routes/sale.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashDealsRoute = FlashDealsRouteImport.update({
  id: '/flash-deals',
  path: '/flash-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCalendarRoute = SalesCalendarRouteImport.update({
  id: '/sales-calendar',
  path: '/sales-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DealSlugRoute = DealSlugRouteImport.update({
  id: '/deal/$slug',
  path: '/deal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleSlugRoute = SaleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SaleRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/flash-deals': typeof FlashDealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/sale': typeof SaleRouteWithChildren
  '/sales-calendar': typeof SalesCalendarRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/deal/$slug': typeof DealSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/flash-deals': typeof FlashDealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/sale': typeof SaleRouteWithChildren
  '/sales-calendar': typeof SalesCalendarRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/deal/$slug': typeof DealSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/flash-deals': typeof FlashDealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/sale': typeof SaleRouteWithChildren
  '/sales-calendar': typeof SalesCalendarRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/deal/$slug': typeof DealSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/brands'
    | '/coupons'
    | '/deals'
    | '/flash-deals'
    | '/guides'
    | '/sale'
    | '/sales-calendar'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/brand/$slug'
    | '/category/$slug'
    | '/deal/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/sale/$slug'
    | '/store/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/brands'
    | '/coupons'
    | '/deals'
    | '/flash-deals'
    | '/guides'
    | '/sale'
    | '/sales-calendar'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/brand/$slug'
    | '/category/$slug'
    | '/deal/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/sale/$slug'
    | '/store/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/brands'
    | '/coupons'
    | '/deals'
    | '/flash-deals'
    | '/guides'
    | '/sale'
    | '/sales-calendar'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/brand/$slug'
    | '/category/$slug'
    | '/deal/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/sale/$slug'
    | '/store/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BrandsRoute: typeof BrandsRoute
  CouponsRoute: typeof CouponsRoute
  DealsRoute: typeof DealsRoute
  FlashDealsRoute: typeof FlashDealsRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  SaleRoute: typeof SaleRouteWithChildren
  SalesCalendarRoute: typeof SalesCalendarRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  BrandSlugRoute: typeof BrandSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DealSlugRoute: typeof DealSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-deals': {
      id: '/flash-deals'
      path: '/flash-deals'
      fullPath: '/flash-deals'
      preLoaderRoute: typeof FlashDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-calendar': {
      id: '/sales-calendar'
      path: '/sales-calendar'
      fullPath: '/sales-calendar'
      preLoaderRoute: typeof SalesCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$slug': {
      id: '/deal/$slug'
      path: '/deal/$slug'
      fullPath: '/deal/$slug'
      preLoaderRoute: typeof DealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/$slug': {
      id: '/sale/$slug'
      path: '/$slug'
      fullPath: '/sale/$slug'
      preLoaderRoute: typeof SaleSlugRouteImport
      parentRoute: typeof SaleRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface SaleRouteChildren {
  SaleSlugRoute: typeof SaleSlugRoute
}

const SaleRouteChildren: SaleRouteChildren = {
  SaleSlugRoute: SaleSlugRoute,
}

const SaleRouteWithChildren = SaleRoute._addFileChildren(SaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BrandsRoute: BrandsRoute,
  CouponsRoute: CouponsRoute,
  DealsRoute: DealsRoute,
  FlashDealsRoute: FlashDealsRoute,
  GuidesRoute: GuidesRouteWithChildren,
  SaleRoute: SaleRouteWithChildren,
  SalesCalendarRoute: SalesCalendarRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  BrandSlugRoute: BrandSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  DealSlugRoute: DealSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
