// AUTO-GENERATED by scripts/import-products.ts — do not edit by hand.
// Re-run `npm run import:products -- <csv>` to regenerate.

import type { Product } from "./products";

export const generatedProducts: Product[] = [];
